#!/bin/sh

ln -s $(pwd)/gitconfig ~/.gitconfig

ln -s $(pwd)/vimrc ~/.vimrc
ln -s $(pwd)/vim ~/.vim

mkdir -p ~/.vim/plugged # for pluggins directory
mkdir -p ~/.vim/.backup
mkdir -p ~/.vim/.tmp

# Install https://github.com/junegunn/vim-plug
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
